name: Run acceptance tests on staging
on:
  workflow_dispatch:
jobs:
  acceptance-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies with npm
        working-directory: ./acceptance-test
        run: npm ci
      - name: Run acceptance tests
        working-directory: ./acceptance-test
        run: npm test
        env:
          ACCEPTANCE_TEST_URL: https://dev-staging-strength.silvercrater.dev/
