name: Deploy to production
on:
  workflow_run:
    workflows: ["Build artificat"]
    types: [completed]
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Push static site to downstream repo for deployment
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: build
          destination-github-username: timurtripp
          destination-repository-name: csci5828-strength-frontend-build-prod
          target-branch: main
